### PR TITLE
Update vec.h

### PR DESCRIPTION
**Pull request by matthiascy**
fix a constructor error of 4D vector

### CODE REVIEW

**Comment by ButchDean** [comment]
Hi,

Can you please post the error you are getting and the compiler version? It builds fine for me in its original state, but will double-check when I get home.

Just eyeballing the code it already looks fine.

**Comment by ButchDean** [comment]
Great find! Thanks!

**Comment by matthiascy** [comment]
I was just get up, received you email and preparing to copy some pics to you, but suddenly I find you already merged it. :smile: It will cause the w value to be 0, thus the position will be the direction, while drawing the result will be wired, through out all files, that constructor is not being used. On my machine(Fedora 22, gcc-5.3.1), it doesn't cause compile error but the result is wrong. :smile:

**Comment by ButchDean** [comment]
Perfect. Thank you for the detail too! Will ensure the original author is updated to fix the code for the other platforms. :)

**Pull request merged**
